### ISSUE TITLE
Maven release

### ISSUE THREAD

**Issue by kroeberk** [mailin-api/mailin-api-java#4]
Hello sendinblue team,

since the java library requires another module (aka gson) and copying java classes onto your classpath is just bad style, you should really consider deploying the mailin api in the official maven repositories. 

~Karl

**Comment by emu42** [comment]
I agree. Even if the API is just one class, doing proper release and dependency management is always a good idea. And maven helps you do both.

**Comment by jakubboguslawski** [comment]
100% agree!

**Comment by jorn86** [comment]
Yes please. I won't be able to use this library unless it is available on Maven central.

**Comment by Parvindersib** [comment]
Hello,

Thanks for your suggestions.

We have added our API package in [Mvn central repository](http://search.maven.org/#search|ga|1|g:"com.sendinblue")

Installation [link](https://github.com/mailin-api/sendinblue-java-mvn)


Regards,
Sendinblue Team

**Comment by cdeverre** [comment]
Thank you for the maven integration, but you change one thing: the name of the class from Mailing to Sendinblue.
You should update the README of the 2.0 version in this github, and the documentation in your website accordingly.
