### ISSUE TITLE
Inserting User using create_update_user (email ok, name and surname not updated or inserted)

### ISSUE THREAD

**Issue by loulou1310** [mailin-api/mailin-api-java#5]
Hello,

I've sent an email but i noticed that this was on github.

I am using this part of code using the api :

```
Mailin http = new Mailin("https://api.sendinblue.com/v2.0","XXXXX");
Map < String, String > attributes = new HashMap < String, String > ();
attributes.put("NAME", "TEST");
attributes.put("SURNAME", "TEST2");
Map < String, Object > data = new HashMap < String, Object > ();
data.put("email", "test1234@espacevital.be");
data.put("attributes", attributes);
data.put("listid", new int [] {2});
/* data.put("listid_unlink", new int [] {2,5});*/
	        
String str = http.create_update_user(data);
System.out.println(str);
```

The user is added only in the list i ask for (2) but the other 2 attributes are not set (name and surname)

This is the response :

> {"code":"success","message":"User created successfully. ","data":{"id":8794}}

Am i doing something wrong ?

**Comment by loulou1310** [comment]
Ok never mind since my webclient is in french, i just tried replacing
```
attributes.put("NAME", "TEST");
attributes.put("SURNAME", "TEST2");
```
by
```
attributes.put("NOM", "TEST");
attributes.put("PRENOM", "TEST2");
```
And This time it worked but it seems to me that this should be mentionned on the api doc or NAME and SURNAME should be accepted in any language.

**Comment by ekta-slit** [comment]
Hi @loulou1310 

The attributes passed in API call are the _contact attribute names_ present in your SendinBlue account.
These are not translated as per language, should be passed with same name as created in the account.

Thank you
SendinBlue Team
