### ISSUE TITLE
Emojis do not display when sending SMS

### ISSUE THREAD

**Issue by mwiley63** [mailin-api/mailin-api-java#6]
Thanks for the Java API, it was very handy for getting an SMS framework up and running.

However, I've tried sending emojis using unicode characters in Java (e.g. \uD83D\uDE00) and they show up as a blank space in the SMS message.

Any pointers on handling emojis with this API/code?

Thank you!

**Comment by ekta-slit** [comment]
Hi @mwiley63 

Thank you for contacting us!

We are not supporting emojis. We support normal GSM characters to be sent via SMS and to support emojis we need unicode character support which we don't offer as of now.


Reagrds
SendinBlue Team

**Comment by mwiley63** [comment]
Thanks for the explanation!
